// The stress-test gallery: why Seawall earns its place even though mainnet is
// calm today. One block per real crisis, replayed through the unchanged model.
// All data is static (generated by scripts/backtest-viz.ts from the validated
// reports) — this section reads nothing live and drives nothing.
import { BACKTESTS } from "../backtests";
import { BacktestCase, type BacktestData } from "./BacktestCase";
import { GALLERY_INTRO } from "./backtest-copy";

export function BacktestGallery() {
  const cases = BACKTESTS as readonly unknown[] as BacktestData[];
  if (!cases.length) return null;
  return (
    <div className="bt-gallery">
      <div className="bt-intro">
        <p className="bt-intro-lead">{GALLERY_INTRO.lead}</p>
        <p className="bt-intro-body">{GALLERY_INTRO.body}</p>
        <div className="bt-legend">
          <span className="bt-leg"><span className="bt-leg-line bt-leg-score" /> AI risk score</span>
          <span className="bt-leg"><span className="bt-leg-line bt-leg-ltv" /> max LTV</span>
          <span className="bt-leg"><span className="bt-leg-line bt-leg-cap" /> borrow cap</span>
          <span className="bt-leg"><span className="bt-leg-line bt-leg-div" /> divergence</span>
          <span className="bt-leg"><span className="bt-leg-line bt-leg-price" /> price</span>
          <span className="bt-leg"><span className="bt-leg-mark bt-leg-agent" /> agent → CAUTION</span>
          <span className="bt-leg"><span className="bt-leg-sw bt-leg-freeze" /> contract FROZEN (red until DAO)</span>
        </div>
        <p className="bt-intro-caveat">{GALLERY_INTRO.caveat}</p>
      </div>
      <div className="bt-cases">
        {cases.map((c) => (
          <BacktestCase key={c.key} data={c} />
        ))}
      </div>
    </div>
  );
}
