// The stress-test gallery: why Seawall earns its place even though mainnet is
// calm today. A tight claim-led intro + at-a-glance proof chips, then ONE case
// per real crisis, EACH collapsed under its own spoiler (oct10 — the on-thesis
// precedent — opens by default). All data is static (generated by
// scripts/backtest-viz.ts from the validated reports) — this section reads
// nothing live and drives nothing.
import { BACKTESTS } from "../backtests";
import { BacktestCase, type BacktestData } from "./BacktestCase";
import { GALLERY_INTRO } from "./backtest-copy";

export function BacktestGallery() {
  const cases = BACKTESTS as readonly unknown[] as BacktestData[];
  if (!cases.length) return null;
  return (
    <div className="bt-gallery">
      <div className="bt-intro">
        <p className="bt-intro-body">{GALLERY_INTRO.body}</p>

        {/* at-a-glance verdict — visible even with every case collapsed */}
        <div className="bt-proof">
          <span className="bt-proof-chip is-freeze">2 contract FREEZES · divergence ≥ 5%</span>
          <span className="bt-proof-chip is-caution">3 graded CAUTION tightens · agent, clamped</span>
          <span className="bt-proof-chip is-calm">scores regression-verified vs the validated reports</span>
        </div>

        {/* proxy note — surfaced at the SAME altitude as the freeze claim (not
            buried in the details below): the divergence axis here is a free-history
            stand-in for the live Pyth↔DeepBook signal. */}
        <p className="bt-proxy-note">
          Upfront: the <b>divergence</b> axis here is a free-history proxy — perp last↔index, or spot↔the $1 peg — not
          the live Pyth↔DeepBook signal. Same estimator, closest archived analog; the freeze line is that proxy crossing
          5%. Full methodology below.
        </p>

        {/* honest scope + how-to-read, demoted one click away */}
        <details className="bt-scope">
          <summary>
            <span className="bt-scope-sum">Honest scope &amp; how to read the charts</span>
          </summary>
          <p className="bt-intro-caveat">{GALLERY_INTRO.caveat}</p>
          <p className="bt-foot">
            Price = <b>asset/USD</b> (dark line). BTC is a market-context input, not a pair — its volatility tells a
            systemic crash (asset falls with BTC → borrow cap) from an idiosyncratic one (asset alone → max LTV). All
            times UTC.
          </p>
        </details>
      </div>

      <div className="bt-cases">
        {cases.map((c) => (
          <BacktestCase key={c.key} data={c} defaultOpen={c.key === "oct10"} />
        ))}
      </div>
    </div>
  );
}
