// The stress-test gallery: why Seawall earns its place even though mainnet is
// calm today. A tight claim-led intro + at-a-glance proof chips, then ONE case
// per real crisis, EACH collapsed under its own spoiler (oct10 — the on-thesis
// precedent — opens by default). All data is static (generated by
// scripts/backtest-viz.ts from the validated reports) — this section reads
// nothing live and drives nothing.
import { BACKTESTS } from "../backtests";
import { BacktestCase, type BacktestData } from "./BacktestCase";
import { GALLERY_INTRO } from "./backtest-copy";

export function BacktestGallery() {
  const cases = BACKTESTS as readonly unknown[] as BacktestData[];
  if (!cases.length) return null;
  return (
    <div className="bt-gallery">
      <div className="bt-intro">
        <p className="bt-intro-body">{GALLERY_INTRO.body}</p>

        {/* at-a-glance verdict — visible even with every case collapsed */}
        <div className="bt-proof">
          <span className="bt-proof-chip is-freeze">2 contract FREEZES · divergence ≥ 5%</span>
          <span className="bt-proof-chip is-caution">3 graded CAUTION tightens · agent, clamped</span>
          <span className="bt-proof-chip is-calm">scores regression-verified vs the validated reports</span>
        </div>

        {/* EXPLICIT data-substitution panel — surfaced at the SAME altitude as the
            freeze claim: which source the replays swap in for the live one, in plain
            text, and why the swap is fair. (The full methodology is in the details.) */}
        <div className="bt-swap">
          <div className="bt-swap-head">What the replays swap in — and why it's fair</div>
          <div className="bt-swap-rows">
            <div className="bt-swap-row">
              <span className="bt-swap-tag is-live">live</span>
              <span className="bt-swap-src">
                Pyth oracle price <span className="bt-swap-vs">vs</span> DeepBook order-book mid
                <span className="bt-swap-where"> — on-chain; the breach the contract re-derives itself.</span>
              </span>
            </div>
            <div className="bt-swap-row">
              <span className="bt-swap-tag is-bt">backtest</span>
              <span className="bt-swap-src">
                Binance perp <b>last</b> <span className="bt-swap-vs">vs</span> <b>index</b> price
                <span className="bt-swap-where"> (the crypto crashes)</span>, or Bybit spot{" "}
                <span className="bt-swap-vs">vs</span> a fixed <b>$1.00 peg</b>
                <span className="bt-swap-where"> (the USDC de-peg)</span>.
              </span>
            </div>
          </div>
          <p className="bt-swap-why">
            Only the DeepBook leg is replaced — historical on-chain order-book data is archived nowhere. Everything
            downstream is the live code: the detector is byte-identical (<code>div = 10⁴·|ln a − ln b|</code>, same
            calibration, smoothing and one-way ratchet), and perp&#8209;last&#8209;vs&#8209;index measures the very thing
            an oracle↔CLOB gap does — a venue's traded price coming unglued from the cross-venue fair value. The freeze
            line you see is that proxy crossing 5%. <span className="bt-swap-more">Full methodology below.</span>
          </p>
        </div>

        {/* honest scope + how-to-read, demoted one click away */}
        <details className="bt-scope">
          <summary>
            <span className="bt-scope-sum">Honest scope &amp; how to read the charts</span>
          </summary>
          <p className="bt-intro-caveat">{GALLERY_INTRO.caveat}</p>
          <p className="bt-foot">
            Price = <b>asset/USD</b> (dark line). BTC is a market-context input, not a pair — its volatility tells a
            systemic crash (asset falls with BTC → borrow cap) from an idiosyncratic one (asset alone → max LTV). All
            times UTC.
          </p>
        </details>
      </div>

      <div className="bt-cases">
        {cases.map((c) => (
          <BacktestCase key={c.key} data={c} defaultOpen={c.key === "oct10"} />
        ))}
      </div>
    </div>
  );
}
