// AUTO-GENERATED by packages/agent/scripts/backtest-viz.ts — do not edit by hand.
import feb2025 from "./feb2025.json";
import usdc2023 from "./usdc2023.json";
import oct10 from "./oct10.json";
import aug2024 from "./aug2024.json";
import cetus from "./cetus.json";
export const BACKTESTS = [feb2025, usdc2023, oct10, aug2024, cetus] as const;
export type Backtest = (typeof BACKTESTS)[number];
